name: Publish release workflow

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  publish-release:
    runs-on: macos-latest
    permissions:
      id-token: write # Require to sign SBOM
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Generate SBOM
        run: ./gradlew cyclonedxBom

      - name: Sign SBOM (keyless)
        run: |
          cosign sign-blob \
            --yes \
            core/build/reports/cyclonedx/bom.json \
            --bundle core/build/reports/cyclonedx/bom.json.bundle    

      - name: Publish artifact
        env:
          PUBLISHING_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}

        # GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # Split on '/' and take the 3rd value to get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publishToMavenLocal
